apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: headlamp

resources:
  - 00-namespace.yaml
  - 10-rbac.yaml
  - 20-headlamp.yaml

images:
  - name: ghcr.io/headlamp-k8s/headlamp
    newTag: v0.25.0

commonLabels:
  app.kubernetes.io/managed-by: kustomize
