package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
)

// Class is a Fabric primitive (a "class" in XDM terms): the answer to one
// fundamental question (Who? When? Where? Why? ...).
type Class struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Question string `json:"question,omitempty"`
}

// MetaNode / MetaEdge form the schema graph (the model describing itself).
type MetaNode struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type MetaEdge struct {
	From string `json:"from"`
	Rel  string `json:"rel"`
	To   string `json:"to"`
}

// Model is the canonical Fabric data model, generated by
// codegen/generate_models.py --target json into gen/model.json.
type Model struct {
	Classes []Class    `json:"classes"`
	Nodes   []MetaNode `json:"nodes"`
	Edges   []MetaEdge `json:"edges"`

	genDir string // resolved gen/ directory, for lazy JSON Schema loads
	byName map[string]Class
}

// findGenDir locates the gen/ directory holding model.json. It honours
// FABRIC_ROOT, then walks up from the working directory looking for
// gen/model.json so the binary runs from anywhere in the tree.
func findGenDir() (string, error) {
	if root := os.Getenv("FABRIC_ROOT"); root != "" {
		return filepath.Join(root, "gen"), nil
	}
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		cand := filepath.Join(dir, "gen", "model.json")
		if _, err := os.Stat(cand); err == nil {
			return filepath.Join(dir, "gen"), nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", os.ErrNotExist
		}
		dir = parent
	}
}

// LoadModel reads and indexes gen/model.json.
func LoadModel() (*Model, error) {
	genDir, err := findGenDir()
	if err != nil {
		return nil, err
	}
	b, err := os.ReadFile(filepath.Join(genDir, "model.json"))
	if err != nil {
		return nil, err
	}
	var m Model
	if err := json.Unmarshal(b, &m); err != nil {
		return nil, err
	}
	m.genDir = genDir
	m.byName = make(map[string]Class, len(m.Classes))
	for _, c := range m.Classes {
		m.byName[c.ID] = c
	}
	return &m, nil
}

// Class returns one primitive by short id (e.g. "identity"), or false.
func (m *Model) Class(name string) (Class, bool) {
	c, ok := m.byName[name]
	return c, ok
}

// Schema returns the generated JSON Schema for a primitive as raw JSON, lazily
// read from gen/jsonschema/{name}.json.
func (m *Model) Schema(name string) (json.RawMessage, error) {
	b, err := os.ReadFile(filepath.Join(m.genDir, "jsonschema", name+".json"))
	if err != nil {
		return nil, err
	}
	return json.RawMessage(b), nil
}

// Resolution is the connected subgraph reached by walking the schema graph.
type Resolution struct {
	Start    string     `json:"start"`
	Depth    int        `json:"depth"`
	Resolved []string   `json:"resolved"`
	Edges    []MetaEdge `json:"edges"`
}

// Resolve walks the model's relationship graph breadth-first from a node,
// mirroring api/server.py's resolve(): follows outgoing edges to `depth` hops.
func (m *Model) Resolve(name string, depth int) (*Resolution, bool) {
	known := map[string]bool{}
	for _, n := range m.Nodes {
		known[n.ID] = true
	}
	if !known[name] {
		return nil, false
	}
	adj := map[string][]MetaEdge{}
	for _, e := range m.Edges {
		adj[e.From] = append(adj[e.From], e)
	}
	visited := map[string]bool{name: true}
	var path []MetaEdge
	type item struct {
		id string
		d  int
	}
	queue := []item{{name, 0}}
	for len(queue) > 0 {
		cur := queue[0]
		queue = queue[1:]
		if cur.d >= depth {
			continue
		}
		for _, e := range adj[cur.id] {
			path = append(path, e)
			if !visited[e.To] {
				visited[e.To] = true
				queue = append(queue, item{e.To, cur.d + 1})
			}
		}
	}
	resolved := make([]string, 0, len(visited))
	for v := range visited {
		resolved = append(resolved, v)
	}
	sort.Strings(resolved)
	return &Resolution{Start: name, Depth: depth, Resolved: resolved, Edges: path}, true
}

// Seed loads the canonical model into the runtime graph so the platform is
// self-describing: each primitive becomes a record in table "primitive" and
// each schema edge becomes a graph edge. This meta layer is not persisted to
// the log — it is re-seeded from gen/model.json on every boot.
func (m *Model) Seed(g *Graph) {
	for _, n := range m.Nodes {
		c, _ := m.Class(n.ID)
		g.Put(&Record{
			Table: "primitive",
			ID:    "primitive:" + n.ID,
			Fields: map[string]any{
				"name":     n.Name,
				"question": c.Question,
			},
		}, false)
	}
	for _, e := range m.Edges {
		g.Relate(&Edge{
			Rel:  e.Rel,
			From: "primitive:" + e.From,
			To:   "primitive:" + e.To,
		}, false)
	}
}
