{{- if and .Values.database.external.enabled (not .Values.database.external.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "liferay.fullname" . }}-db
  labels:
    {{- include "liferay.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.external.password | b64enc | quote }}
{{- end }}
